import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // AWS画像処理ハンズオン専用のサイドバー
  handsonSidebar: [
    {
      type: 'doc',
      id: 'handson/index',
      label: '🚀 ハンズオン概要',
    },
    {
      type: 'doc',
      id: 'handson/preparation',
      label: '🔧 事前準備・環境確認',
    },
    {
      type: 'category',
      label: '📚 実装ステップ',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'handson/s3-bucket',
          label: 'Step 1: S3バケット作成',
        },
        {
          type: 'doc',
          id: 'handson/dynamodb',
          label: 'Step 2: DynamoDB設定',
        },
        {
          type: 'doc',
          id: 'handson/lambda',
          label: 'Step 3: Lambda関数作成',
        },
        {
          type: 'doc',
          id: 'handson/s3-event',
          label: 'Step 4: S3イベント設定',
        },
        {
          type: 'doc',
          id: 'handson/cloudfront',
          label: 'Step 5: CloudFront設定',
        },
        {
          type: 'doc',
          id: 'handson/test',
          label: 'Step 6: システムテスト',
        },
      ],
    },
    {
      type: 'category',
      label: '🛠️ サポート',
      collapsed: true,
      items: [
        {
          type: 'doc',
          id: 'handson/troubleshooting',
          label: 'Step 7: トラブルシューティング',
        },
        {
          type: 'doc',
          id: 'handson/cleanup',
          label: 'Step 8: 後片付け',
        },
      ],
    },
  ],
};

export default sidebars;
